title: rainygirl's Op-eds
description: >
    Software Engineer, Technology Journalist based in Seoul
author: rainygirl
email: rainygirl@gmail.com
baseurl: "" 
url: "https://rainygirl.github.io" 

include: [_pages]
future: true
permalink: /:year/:month/:title
sass:
    style: compressed

plugins:
  - jemoji
  - jekyll-sitemap
  - amp-jekyll

google_analytics: G-RQBZDH74KC

