title: rainygirl's Op-eds
description: >
    Software Engineer, Technology Journalist based in Seoul
author: rainygirl
email: rainygirl@gmail.com
baseurl: "" 
url: "https://rainygirl.github.io" 

include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title
sass:
    style: compressed

gems:
  - jemoji
  - jekyll-sitemap
  - amp-jekyll 

ampdir: amp/
enable_amp: true

google_analytics: UA-19555082-3

